### ISSUE TITLE
On Places search, there's English text

### ISSUE THREAD

**Issue by lgontard** [ytgov/yukon-ca#828]
On the Places search, there's a header that should be in French
"Places listing" should be "Établissements, installations et bureaux"
![image](https://github.com/user-attachments/assets/250acb32-8884-417b-80a9-000165b46730)

**Comment by leeomara** [comment]
UAT now shows:

> Établissements, Installations Et Bureaux

https://yukon.cms-uat.yukon.ca/fr/etablissements-installations-et-bureaux

I notice that it's capitalized, via CSS

```css
main > .row .layout-content .block-views-blockplaces-listing-block-places-listing .block-title {
  margin-top: .9375rem;
  margin-bottom: .75rem;
  font-size: 26px;
  font-weight: 500;
  text-transform: capitalize;
}
```

That is wrong. I wonder how long that's been there?
